### ISSUE TITLE
Cannot run app without sudo in Big Sur (macOS 11.0.1)

### ISSUE THREAD

**Issue by bountycortez** [K-Visscher/pro-intellimouse-control-panel#10]
Before I start: Great job, i love Intellimouse (best MS product ever) an am very happy that i found your repo. 

In Big Sur (macOS 11.0.1) it seems, that up to now, Apple has problems with a mouse polling rate >125.
So i was looking for a solution. One way would have been to configure the mouse in windows 10.
But especially since i'm in homeoffice (we have currently a covid lockdown here in austria) i cannot plugin my mouse to a windows workstation. 

So i tried your solution and i was able to build the App in Big Sur, but i can only run it in Terminal with sudo:
sudo ~/Desktop/microsoft-intellimouse-pro-control-panel.app/Contents/MacOS/microsoft-intellimouse-pro-control-panel
(Then i was able to set polling rate, led color, etc.)

Otherwise there is i assume a problem with the rights and the app tells only that something went wrong.
<img width="294" alt="Bildschirmfoto 2020-11-23 um 14 01 18" src="https://user-images.githubusercontent.com/59827321/99965060-97caeb80-2d94-11eb-9f6f-54ed6ca7064d.png">

**Comment by K-Visscher** [comment]
Sorry for my late response.

Yeah, I don't think there's a simple way on macOS to get around using `sudo` unfortunately.
I believe this issues is caused because the OS instantly claims the USB HID interfaces using its own generic drivers, you could theoretically solve this by making a codeless kext that claims the intellimouse's interfaces. However that's a bit of a sketchy procedure and you'll have disable security features. If you have an Apple developer account you can make a signed kext, that doesn't require you disabling all kinds of security features but I'm not certain on this. But i'm not spending any money on that i'm afraid :P

There are things out there like [elevate](https://pypi.org/project/elevate/) that are quite nice and should make it more clear that sudo is required on macOS and automate the process, but I haven't yet succeeded in it playing nice together with fbs/PyQt, beacuse it launches a new process.

**Comment by sauron918** [comment]
Hi, 

Same for me... Cannot run app in Big Sur 11.6. Get
```
Traceback (most recent call last):
  File "main.py", line 95, in <module>
  File "main.py", line 31, in __init__
  File "intellimouse.py", line 43, in get_polling_rate
  File "usb/core.py", line 1034, in ctrl_transfer
  File "usb/core.py", line 102, in wrapper
  File "usb/core.py", line 167, in managed_claim_interface
  File "usb/backend/libusb1.py", line 811, in claim_interface
  File "usb/backend/libusb1.py", line 595, in _check
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)
[4708] Failed to execute script main
```
on sudo `./ProIntelliMouseDriver.app/Contents/MacOS/ProIntelliMouseDriver`
